import type { Metadata } from "next";
import { DM_Sans, Inter, Roboto } from "next/font/google";
import Provider, { ConfigTheme } from "./providers";

const dmsans = DM_Sans({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  preload: false
})
export const metadata: Metadata = {
  title: "Welcome to DreyerX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmsans.className} style={{ scrollBehavior: 'smooth' }}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
